name: 'Package installation testing'
description: 'Test that given package can be installed from a given repo'
inputs:
  repo_base_url:
    description: 'base url to the rpm/yum/apt repository of NR'
    required: true
  package_name:
    description: 'name of a package'
    required: true
  package_version:
    description: 'version of a package that should be installed'
    required: true
  gpg_key:
    description: 'gpg key to verify package signatures'
    required: true
  platforms:
    description: 'comma separated list of platforms with version we want to run test for'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure Molecule and Ansible
      shell: bash
      run: |
        python3 -m pip install molecule==24.2.1 ansible==9.5.1 ansible-core==2.16.6 "molecule-plugins[docker]==23.5.3"
    - name: Prepare OS versions
      shell: bash
      run: ${GITHUB_ACTION_PATH}/prepare_platform.sh ${{ inputs.platforms }}
    - name: Run molecule
      shell: bash
      env:
        REPO_BASE_URL: ${{ inputs.repo_base_url }}
        PACKAGE_NAME: ${{ inputs.package_name }}
        PACKAGE_VERSION: ${{ inputs.package_version }}
        GPG_KEY: ${{ inputs.gpg_key }}
      run: "cd ${GITHUB_ACTION_PATH} && molecule converge"
    - name: Teardown
      shell: bash
      run: "cd ${GITHUB_ACTION_PATH} && molecule destroy"
