---
- name: Converge
  hosts: all
  tasks:
    - name: Installation tests suite
      vars:
        repo_endpoint: "{{ lookup('env', 'REPO_BASE_URL') }}"
        package_version: "1.67.0-rhel10-test"
        package_name: "{{ lookup('env', 'PACKAGE_NAME') }}"
        gpg_key: "{{ lookup('env', 'GPG_KEY') }}"
        exec_name: "{{ lookup('env', 'EXEC_NAME') }}"

      block:
        - name: Repo setup
          include_role:
            name: caos.ansible_roles.nr_repo_setup

        - name: Install package
          include_role:
            name: caos.ansible_roles.package_install
          vars:
            package: "{{ package_name }}"
            target_version: "{{ package_version }}"
            
        - name: assert version
          include_role:
            name: caos.ansible_roles.assert_version
          vars:
            target_versions:
              - exec: "{{ exec_name }} --version"
                version: "{{ package_version }}"

